import Spire from "./classes/spire.js";

import "./components/dialog.js";
import "./components/s-accordion.js";
import "./components/s-avatar.js";
import "./components/s-backdrop.js";
import "./components/s-box.js";
import "./components/s-button.js";
import "./components/s-buttons.js";
import "./components/s-card.js";
import "./components/s-checkbox.js";
import "./components/s-content.js";
import "./components/s-contextmenu.js";
import "./components/s-drawer.js";
import "./components/s-footer.js";
import "./components/s-header.js";
import "./components/s-icon.js";
import "./components/s-label.js";
import "./components/s-layout.js";
import "./components/s-message.js";
import "./components/s-menu.js";
import "./components/s-menubar.js";
import "./components/s-menuitem.js";
import "./components/s-nav.js";
import "./components/s-navitem.js";
import "./components/s-notification.js";
import "./components/s-numberinput.js";
import "./components/s-pager.js";
import "./components/s-popover.js";
import "./components/s-progressbar.js";
import "./components/s-radio.js";
import "./components/s-radios.js";
import "./components/s-sidebar.js";
import "./components/s-tooltip.js";

export default Spire;
